BootstrapIntroduction/Models/Author.cs
using Newtonsoft.Json;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BootstrapIntroduction.Models
{
    public class Author
    {

        [JsonProperty(PropertyName ="id")]
        public int Id { get; set; }

        [Required]
        [JsonProperty(PropertyName = "firstName")]
        public string FirstName { get; set; }

        [Required]
        [JsonProperty(PropertyName = "lastName")]
        public string LastName { get; set; }

        [JsonProperty(PropertyName = "biography")]
        public string Biography { get; set; }

        [JsonProperty(PropertyName = "books")]
        public virtual ICollection<Book> Books { get; set; }

    }
}

BootstrapIntroduction/ViewModels/AuthorViewModel.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BootstrapIntroduction.ViewModels
{
    public class AuthorViewModel
    {
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        [Required]
        [JsonProperty(PropertyName = "firstName")]
        public string FirstName { get; set; }

        [Required]
        [JsonProperty(PropertyName = "lastName")]
        public string LastName { get; set; }

        [JsonProperty(PropertyName = "biography")]
        public string Biography { get; set; }
    }
}

BootstrapIntroduction/Controllers/AuthorsController.cs
using AutoMapper;
using BootstrapIntroduction.DAL;
using BootstrapIntroduction.Filters;
using BootstrapIntroduction.Models;
using BootstrapIntroduction.Services;
using BootstrapIntroduction.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Web;
using System.Web.ModelBinding;
using System.Web.Mvc;

namespace BootstrapIntroduction.Controllers
{
    [RoutePrefix("Writer")]
    public class AuthorsController : Controller
    {

        private AuthorService authorService;
        private MapperConfiguration configuration;

        public AuthorsController()
        {
            authorService = new AuthorService();


            configuration = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Author, AuthorViewModel>();
            });

        }

        // GET: Authors
        [GenerateResultListFilter(typeof(Author), typeof(AuthorViewModel))]
        [Route("~/Writers")]
        public ActionResult Index([Form] QueryOptions queryOptions)
        {
            var authors = authorService.Get(queryOptions);

            ViewData["QueryOptions"] = queryOptions;

            return View(authors.ToList());
        }

        [Route("Details/{id:int:min(0)?}")]
        public ActionResult Details(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            var autor = authorService.GetById(id.Value);

            if(autor == null)
            {
                throw new System.Data.Entity.Core.ObjectNotFoundException($"Unable to find author with id {id}");
            }
            var mapper = configuration.CreateMapper();

            return View("Form",mapper.Map<Author,AuthorViewModel>(autor));
        }

        [BasicAuthorization]
        public ActionResult Create()
        {
            return View("Form", new AuthorViewModel());
        }

        [BasicAuthorization]
        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var author = authorService.GetById(id.Value);

            if(author == null)
            {
                return HttpNotFound();
            }

            var mapper = configuration.CreateMapper();

            return View("Form", mapper.Map<Author,AuthorViewModel>(author));
        }

        
        [BasicAuthorization]
        public ActionResult Delete(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var author = authorService.GetById(id.Value);

            if(author == null)
            {
                return HttpNotFound();
            }
            var mapper = configuration.CreateMapper();

            return View(mapper.Map<Author, AuthorViewModel>(author));
        }
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [BasicAuthorization]
        public ActionResult DeleteConfirmed(int id)
        {
            var author = authorService.GetById(id);

            authorService.Delete(author);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                authorService.Dispose();

            base.Dispose(disposing);
        }




    }
}

BootstrapIntroduction/Controllers/api/AuthorsController.cs
using AutoMapper;
using BootstrapIntroduction.DAL;
using BootstrapIntroduction.Models;
using BootstrapIntroduction.Services;
using BootstrapIntroduction.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;

namespace BootstrapIntroduction.Controllers.api
{
    public class AuthorsController : ApiController
    {
        
        private AuthorService authorService;
        private MapperConfiguration configuration;
        private IMapper mapper;
        public AuthorsController()
        {

            authorService = new AuthorService();
            var configuration = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Author, AuthorViewModel>();
                cfg.CreateMap<AuthorViewModel,Author>();
            });

            mapper = configuration.CreateMapper();

        }

        public ResultList<AuthorViewModel> Get([FromUri] QueryOptions queryOptions)
        {
            var authors = authorService.Get(queryOptions);
            return new ResultList<AuthorViewModel>(
                    mapper.Map<List<Author>, List<AuthorViewModel>>(authors), queryOptions
                );
        }

        [ResponseType(typeof(AuthorViewModel))]
        public IHttpActionResult Get(int id )
        {

            var author = authorService.GetById(id);

            if(author == null)
            {
                throw new System.Data.Entity.Core.ObjectNotFoundException($"Unable to find author with id {id}");
            }

           
            return Ok(mapper.Map<Author,AuthorViewModel>(author));
        } 
        
        [ResponseType(typeof(void))]
        public IHttpActionResult Put(AuthorViewModel author)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            authorService.Update(mapper.Map<AuthorViewModel, Author>(author));

            return StatusCode(HttpStatusCode.NoContent);
        }



        public IHttpActionResult Post(AuthorViewModel author)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            authorService.Insert(mapper.Map<AuthorViewModel, Author>(author));

            return CreatedAtRoute("DefaultApi", new { id = author.Id }, author);

        }

        [ResponseType(typeof(Author))]
        public IHttpActionResult DeleteAuthor(int id)
        {

            var author = authorService.GetById(id);
            authorService.Delete(author);

            return Ok(author);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                authorService.Dispose();

            base.Dispose(disposing);             
        }

    }
}

BootstrapIntroduction/Views/Authors/Delete.cshtml
@model BootstrapIntroduction.ViewModels.AuthorViewModel
    @{
        ViewBag.Title = "Delete";
        Layout = null;
    }

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h3 class="modal-title">Author Delete Confirmation</h3>
                </div>
                <div class="modal-body">
                    <h4>Are you sure you want to delete this author ?</h4>
                    <div>
                        <hr />
                        <dl class="dl-horizontal">

                            <dt>
                                @Html.DisplayNameFor(model => model.FirstName)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.FirstName)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.LastName)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.LastName)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Biography)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Biography)
                            </dd>
                        </dl>
                    </div>
                </div>
                <div class="modal-footer">

                    @using (Html.BeginForm("Delete","Authors",FormMethod.Post, new { data_bind = "submit: deleteAuthor" }))
                    {

                        @Html.AntiForgeryToken()


                        <div class="form-actions no-color text-center" data-bind="visible: !sending()">
                            <input type="submit" value="Delete" class="btn btn-danger" />
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                            
                        <div class="progress" data-bind="visible: sending">
                            <div class="progress-bar progress-bar-info progress-bar-striped active"
                                 role="progressbar" aria-valuenow="100"
                                 aria-valuemin="0"  aria-valuemax="100"
                                 style="width: 100%">
                                <span class="sr-only"></span>
                            </div>
                        </div>

                    }
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

BootstrapIntroduction/Views/Authors/Form.cshtml
@using BootstrapIntroduction.Extensions
@model BootstrapIntroduction.ViewModels.AuthorViewModel

@{
    var isCreating = Model.Id == 0;
    ViewBag.Title = isCreating ? "Create" : "Edit";

    var btnSubmitText = isCreating ? "Create" : "Update";
}



<div data-bind="visible: !saveCompleted()">

    <h2>@ViewBag.Title</h2>

    @using (Html.BeginForm("Create", "Authors", FormMethod.Post, new { data_bind = "submit: validateAndSave" }))
    {
        @Html.AntiForgeryToken();


        <div class="form-horizontal">
            <h4>Author</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(m => m.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(m => m.FirstName, new { htmlAttributes = new { @class = "form-control", data_bind = "value: author.firstName" } })
                    @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "text-danger" })

                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(m => m.LastName, new { htmlAttributes = new { @class = "form-control", data_bind = "value: author.lastName" } })
                    @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Biography, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(m => m.Biography, new { htmlAttributes = new { @class = "form-control", data_bind = "value: author.biography" } })
                    @Html.ValidationMessageFor(m => m.Biography, "", new { @class = "text-danger" })

                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10" data-bind="visible: !sending()">
                    <input type="submit" value="@btnSubmitText" class="btn btn-default" />
                </div>

                <div class="progress" data-bind="visible: sending">
                    <div class="progress-bar progress-bar-info progress-bar-striped active"
                         role="progressbar"
                         aria-valuenow="100"
                         aria-valuemin="0"
                         aria-valuemax="100"
                         style="width: 100%">
                        <span class="sr-only"></span>
                    </div>

                </div>
            </div>
        </div>

    }
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts{


    @Scripts.Render("~/bundles/jqueryval", "~/Scripts/ViewModels/AuthorFormViewModel.js")
    <script>
        var viewModel = new AuthorFormViewModel(@Html.HtmlConvertToJson(Model));
        ko.applyBindings(viewModel)
    </script>
}

BootstrapIntroduction/Views/Authors/Index.cshtml
@using BootstrapIntroduction.ViewModels
@using BootstrapIntroduction.Extensions

@model ResultList<AuthorViewModel>

@{
    ViewBag.Title = "Authors";
    var queryOptions = Model.QueryOptions;
}

<h2>Authors</h2>

<p>@Html.ActionLink("Create New","Create")</p>


<div style="display: none" data-bind="visible: pagingService.entities().length > 0">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>@Html.BuildKnockoutSortableLink("First Name", "Index", "firstName")</th>
                <th>@Html.BuildKnockoutSortableLink("Last Name", "Index", "lastName")</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody data-bind="foreach: pagingService.entities">
            <tr>
                <td data-bind="text: firstName"></td>
                <td data-bind="text: lastName"></td>
                <td>
                    <a data-bind="attr: { href: '@Url.Action("Details")/'+id}" class="btn btn-info">Details</a>
                    <a data-bind="attr: { href: '@Url.Action("Edit")/'+id}" class="btn btn-primary">Edit</a>
                    <a data-bind="click: $parent.showDeleteModal,attr: { href: '@Url.Action("Delete")/'+id}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        </tbody>
    </table>

    @Html.BuildKnockoutNextPreviousLinks("Index")
</div>

<div style="display: none" data-bind="visible: pagingService.entities().length === 0"
     class="alert alert-warning alert-dismissable" role="alert">
    <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">&times;</span>
    </button>
    There are no authors to display.
        Click @Html.ActionLink("Here", "Create") to create one now.
</div>

@section Scripts {
    @Scripts.Render("~/Scripts/Services/PagingService.js", "~/Scripts/ViewModels/AuthorIndexViewModel.js")
<script>

   
    var viewModel = new AuthorIndexViewModel(@Html.HtmlConvertToJson(Model));
    ko.applyBindings(viewModel)
</script>    
}